
server:
  servlet:
    session:
      cookie:
        same-site: none
  port: 8080
#-------------------------------------------- < HIBERNATE > --------------------------------------------------
spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://db:3307/db_1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: user123
    driver-class-name: com.mysql.cj.jdbc.Driver
    #-------------------------------------------- < EMAIL > --------------------------------------------------
  mail:
    host: smtp.gmail.com
    username: jakubmarjankowski0@gmail.com
    password: gmxt ldja dtpt tclx
    port: 587
    protocol: smtp
    properties:
      mail.smtps.auth: true
      mail.smtp.starttls.enable: true

#-------------------------------------------- < TOKENS > --------------------------------------------------

activation-mail-expiration-time: 300000000000
tokens:
  access:
    expiration_time_ms: 300000
  refresh:
    expiration_time_ms: 86400000
    access_token_expiration_time_ms_property: 'access_token_expiration_time_ms_property'
  prefix: 'Bearer '

  #-------------------------------------------- < ADMIN > --------------------------------------------------
admin:
  username: 'admin'
  password: 'admin123'
  name: 'admin'
  surname: 'admin'
  email: 'jakubmarjankowski@gmail.com'
  age: 35

  #-------------------------------------------- < VALIDATE > --------------------------------------------------
validate:
  regex:
    name: '[a-zA-Z]+'
    surname: '[a-zA-Z]+'
    username: '[a-zA-Z0-9]+'
    email: '[\w\.\-]+@([a-z]{2,8}\.){1,2}[a-z]{2,6}'
    password: >
      [A-Z],
      [a-z],
      [0-9],
      [!@#$%^&*?]
  min.age: 18
  password:
    min.length: 8